# Generated by Django 3.2.6 on 2021-09-25 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0003_article_like'),
        ('likeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikeRecord',
        ),
    ]
